name: CMX test

on:
  workflow_dispatch: 

jobs:
  compatibility-matrix:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        cluster: [ {distribution: kind, version: v1.25.3}, {distribution: kind, version: v1.26.3}]
    steps:

      - name: Create Cluster
        id: create-cluster
        uses: replicatedhq/replicated-actions/create-cluster@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          cluster-name: ${{ matrix.cluster.distribution }}-${{ matrix.cluster.version }}
          timeout-minutes: 5
          ttl: 10m
          #export-kubeconfig: true

